version: "3.7"
services:
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
  server:
    build:
      context: .
      dockerfile: Dockerfile
    image: questions-and-answers-server:1.1
    depends_on:
      - database
    ports:
      - "8080:8080"
volumes:
  data:
